version: '3.5'

services:
  todo-list-postgres:
    image: postgis/postgis
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo-list
    volumes:
      - todo-list-db:/var/lib/postgresql/march-2023

volumes:
  todo-list-db:
